# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jiankaoduan.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_1(object):
    def setupUi_2(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(917, 621)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 450, 841, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_11.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_11.setSizePolicy(sizePolicy)
        self.doubleSpinBox_11.setMinimumSize(QtCore.QSize(162, 50))
        self.doubleSpinBox_11.setDecimals(1)
        self.doubleSpinBox_11.setMaximum(10.0)
        self.doubleSpinBox_11.setSingleStep(0.1)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_11)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.doubleSpinBox_12.setMinimumSize(QtCore.QSize(162, 50))
        self.doubleSpinBox_12.setDecimals(1)
        self.doubleSpinBox_12.setMaximum(10.0)
        self.doubleSpinBox_12.setSingleStep(0.1)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_12)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.doubleSpinBox_13.setMinimumSize(QtCore.QSize(162, 50))
        self.doubleSpinBox_13.setDecimals(1)
        self.doubleSpinBox_13.setMaximum(10.0)
        self.doubleSpinBox_13.setSingleStep(0.1)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_13)
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.doubleSpinBox_14.setMinimumSize(QtCore.QSize(162, 50))
        self.doubleSpinBox_14.setDecimals(1)
        self.doubleSpinBox_14.setMaximum(10.0)
        self.doubleSpinBox_14.setSingleStep(0.1)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_14)
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.doubleSpinBox_15.setMinimumSize(QtCore.QSize(162, 50))
        self.doubleSpinBox_15.setDecimals(1)
        self.doubleSpinBox_15.setMaximum(10.0)
        self.doubleSpinBox_15.setSingleStep(0.1)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_15)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 380, 841, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.checkBox_11.setChecked(False)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_10.addWidget(self.checkBox_11, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_12 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_10.addWidget(self.checkBox_12, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_13 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_10.addWidget(self.checkBox_13, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_14 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout_10.addWidget(self.checkBox_14, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_15 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.checkBox_15.setObjectName("checkBox_15")
        self.horizontalLayout_10.addWidget(self.checkBox_15, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 310, 841, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAutoFillBackground(False)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21, 0, QtCore.Qt.AlignHCenter)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22, 0, QtCore.Qt.AlignHCenter)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23, 0, QtCore.Qt.AlignHCenter)
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24, 0, QtCore.Qt.AlignHCenter)
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_11.addWidget(self.label_25, 0, QtCore.Qt.AlignHCenter)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(380, 550, 161, 51))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 841, 251))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("image/example.jpg"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_12.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("image/example.jpg"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_12.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("image/example.jpg"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_12.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("image/example.jpg"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_12.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("image/example.jpg"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_12.addWidget(self.label_30)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox_11.setText(_translate("Dialog", "已提交"))
        self.checkBox_12.setText(_translate("Dialog", "已提交"))
        self.checkBox_13.setText(_translate("Dialog", "已提交"))
        self.checkBox_14.setText(_translate("Dialog", "已提交"))
        self.checkBox_15.setText(_translate("Dialog", "已提交"))
        self.label_21.setText(_translate("Dialog", "考官一"))
        self.label_22.setText(_translate("Dialog", "考官二"))
        self.label_23.setText(_translate("Dialog", "考官三"))
        self.label_24.setText(_translate("Dialog", "考官四"))
        self.label_25.setText(_translate("Dialog", "考官五"))
        self.pushButton.setText(_translate("Dialog", "确认"))

